### ISSUE TITLE
should use 21.08 (i.e. 2021) runtime

### ISSUE THREAD

**Issue by smcv** [flathub/com.valvesoftware.SteamLink#24]
We should move from the 20.08 to 21.08 freedesktop.org SDK at some point. That's a potentially destabilising change, so we should do it when @slouken isn't trying to release new binaries.

**Comment by slouken** [comment]
What's the benefit of moving to a new SDK?

**Comment by nanonyme** [comment]
I would clarify the policy is CVE fixes are done for two years for any given freedesktop-sdk version. This includes crypto libraries and other security-critical components.  Not using latest runtime most likely means app won't work on latest GPU's (especially AMD and Intel) due to obsolete LLVM and Mesa.
