### ISSUE TITLE
Force Xwayland on Wayland

### ISSUE THREAD

**Issue by lhindir** [flathub/com.valvesoftware.SteamLink#6]
When a user with `QT_QPA_PLATFORM=wayland` in their environment runs this application, it crashes with `qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`. It might be a good idea to set this environment variable to `xcb` as in https://github.com/flathub/org.keepassxc.KeePassXC/pull/71/files.

**Comment by smcv** [comment]
> When a user with `QT_QPA_PLATFORM=wayland` in their environment runs this application, it crashes with `qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`. It might be a good idea to set this environment variable to `xcb` as in https://github.com/flathub/org.keepassxc.KeePassXC/pull/71/files.

As a short term solution, we've done that.

As a longer term solution, we should build the Wayland integration plugin for the included version of Qt, so that we're using Wayland whenever possible, or X11 if no Wayland is available. This seems to work OK in some brief testing on GNOME Shell 3.38.x. When we have a beta version that behaves like this, would you mind trying it in your Wayland environment?

**Comment by lhindir** [comment]
I'd be happy to! Thanks for the quick resolution :)

**Comment by smcv** [comment]
> As a short term solution, we've done that.

Closing this issue for now, I'll open a separate one for trying to use Wayland.

**Comment by smcv** [comment]
#15 and #16 are follow-ups from this, making the Steam Link app try to use Wayland instead of X11.

Note that the "server" end of Steam Link (the fully-featured Steam client where your games are launched) still needs to be running under X11: capturing Wayland frames with Pipewire is not supported at the moment.

**Comment by lhindir** [comment]
Thanks, I was going to ask about Wayland hosts. Is there an issue I can follow for this?

I'm not sure if it will affect this, but I also have Wayland issues with the Steam client around controllers, like not being able to navigate the desktop with a Steam Controller managed by Steam, and Xbox controllers not being recognized unless they are connected before Steam is launched. Are there issues I can follow for input problems like this?

**Comment by smcv** [comment]
> Thanks, I was going to ask about Wayland hosts. Is there an issue I can follow for this?

Yes, but it's in the steam-for-linux "server" rather than the Steam Link client. The part that is packaged here is only the "client" end of the connection, and is entirely (or at least, mostly) Wayland-friendly, as far as I can see.

https://github.com/ValveSoftware/steam-for-linux/issues/6148 seems to be the issue you're looking for.

The ideal Wayland-friendly approach would be for Steam to be capturing frames using Pipewire, potentially via xdg-desktop-portal, similar to Flatpak apps that implement screen-sharing. Again, this would be a feature of Steam (requested in the steam-for-linux issue tracker), and would not involve changes to this Steam Link client.

> I'm not sure if it will affect this, but I also have Wayland issues with the Steam client around controllers, like not being able to navigate the desktop with a Steam Controller managed by Steam, and Xbox controllers not being recognized unless they are connected before Steam is launched. Are there issues I can follow for input problems like this?

If there are, they would also be in the steam-for-linux issue tracker, not here.
